on:
  workflow_call:

env:
  count: 4

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ vars.NAME == '' }}
        id: validate-env-not-empty
        run: exit 1
      - id: print-input
        run: echo ${{ vars.NAME }}

        
      - id: test
        shell: bash
        run: python3 -c "print(${{ vars }})"
