on:
  workflow_call:

env:
  count: 4

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ vars.NAME == '' }}
        name: validate-env-not-empty
        run: exit 1
      - id: print-input
        run: echo ${{ vars.NAME }}

      # - id: test
      #   shell: bash
      #   run: echo ${{ toJson(vars) }}

      - name: print-env-if-true-typecasted
        if: ${{ toJson(vars.BOOLEAN_VAR) }}
        shell: bash
        run: echo ${{ toJson(vars.BOOLEAN_VAR) }}

      - name: print-env-if-false-typecasted
        if: ${{ ! toJson(vars.BOOLEAN_VAR) }}
        shell: bash
        run: |
          echo ${{ toJson(vars.BOOLEAN_VAR) }}

      - name: print-env-if-true
        if: ${{ vars.BOOLEAN_VAR }}
        shell: bash
        run: echo ${{ vars.BOOLEAN_VAR }}

      - id: print-env-if-false
        if: ${{ ! vars.BOOLEAN_VAR }}
        shell: bash
        run: |
          echo ${{ vars.BOOLEAN_VAR }}

      - name: test-python
        shell: bash
        run: |
          python3 - <<EOF
          import json
          import sys
          input = ${{ toJson(vars) }}
          print(input)
          print(input.get(BOOLEAN_VAR))

          sys.exit(0)
          EOF
        # run: python3 -c "import json; print(json.loads('${{ toJson(vars) }}'))"
